// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "authors" => http://localhost:9033/admin/info/authors
// "blog_article" => http://localhost:9033/admin/info/blog_article
// "blog_auth" => http://localhost:9033/admin/info/blog_auth
// "blog_tag" => http://localhost:9033/admin/info/blog_tag
// "employee" => http://localhost:9033/admin/info/employee
// "filemanager_setting" => http://localhost:9033/admin/info/filemanager_setting
// "posts" => http://localhost:9033/admin/info/posts
// "profile" => http://localhost:9033/admin/info/profile
// "users" => http://localhost:9033/admin/info/users
//
// example end
var Generators = map[string]table.Generator{

	"authors":             GetAuthorsTable,
	"blog_article":        GetBlogArticleTable,
	"blog_auth":           GetBlogAuthTable,
	"blog_tag":            GetBlogTagTable,
	"employee":            GetEmployeeTable,
	"filemanager_setting": GetFilemanagerSettingTable,
	"posts":               GetPostsTable,
	"profile":             GetProfileTable,
	"users":               GetUsersTable,

	// generators end
}
